seed: 42

# dataset parameters
validation_dataset_proportion: 0.3
test_dataset_proportion: 0.1
dataset_percentage : 0.1
intermediate_forward : false
freeze_beginning : false # should be true if intermediate forward is true
last_frozen_layer : ""
delte_pretrained_model_ending : false # cuts after last frozen layer
intermediate_activation_map_size : [2048, 7, 7] # [2048, 7, 7] for layer4, [1024, 14, 14] for layer3, [512, 28, 28] for layer2

# model parameters
model: resnet18
model_architecture : 
  fully_connected_hidden_layers : [2048, "relu", 1024, "relu", 512, "relu", 256, "relu", 128]
  nb_output_classes : 10
load_checkpoint: false
checkpoint_path : ""

# training parameters
batch_size: 50
learning_rate : 
    initial_value: 0.01
    decrease_on_plateau: true
    patience: 3
weight_decay: 0.00005
nb_epochs : 50

# useful paths and stuff
paths : 
  experiments_folder : experiments
  intermediate_dataset_folder : intermediate
  intermediate_dataset_name : galaxy_activation_maps